DELETE http://localhost:8080/events/1/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3MzA5OTU0NTIsInVzZXJJZCI6MX0.ART05ZO8UxaxR_vyIjrBXwJLVGQyYRRTy_8rW3E6ST0

